### ISSUE TITLE
Feature Request: Add other teleports

### ISSUE THREAD

**Issue by neocryptek** [neveralways/teleport-search#1]
Would you consider adding other teleports (besides the dungeons) to this searchable list?

Ex: Mage portals/teleports, hearthstone, dalaran hearth, etc.

Thanks!

**Comment by neveralways** [comment]
Hello!

Just yesterday, I was talking with a friend about adding this functionality. Specific class portals like the mage portals, the druid portal to Moonglade, the DK portal... It's great to see that more people are interested in this. Thank you so much. :)

**Comment by neveralways** [comment]
Hello again,

I’ve been working on the addon and have implemented the functionalities you requested. Additionally, I’ve updated the addon page to include a Trello workflow so you can easily track the progress and see what’s happening with the addon.

Thanks for comments!
